/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#ffffff',
        'primary-pressed': '#e8e8e8',
        'on-primary': '#000000',
        'ink': '#f4f4f6',
        'body': '#cdcdcd',
        'charcoal': '#d3d3d4',
        'mute': '#9c9c9d',
        'ash': '#6a6b6c',
        'stone': '#434345',
        'on-dark': '#ffffff',
        'on-dark-mute': 'rgba(255,255,255,0.72)',
        'canvas': '#07080a',
        'surface': '#0d0d0d',
        'surface-elevated': '#101111',
        'surface-card': '#121212',
        'button-fg': '#18191a',
        'hairline': '#242728',
        'hairline-soft': 'rgba(255,255,255,0.08)',
        'hairline-strong': 'rgba(255,255,255,0.16)',
        'accent-blue': '#57c1ff',
        'accent-blue-soft': 'rgba(87,193,255,0.15)',
        'accent-red': '#ff6161',
        'accent-red-soft': 'rgba(255,97,97,0.15)',
        'accent-green': '#59d499',
        'accent-green-soft': 'rgba(89,212,153,0.15)',
        'accent-yellow': '#ffc533',
        'accent-yellow-soft': 'rgba(255,197,51,0.15)',
        'hero-stripe-start': '#ff5757',
        'hero-stripe-end': '#a1131a',
        'key-bg-start': '#121212',
        'key-bg-end': '#0d0d0d',
      },
      fontFamily: {
        sans: ['Inter', 'Inter Fallback', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      backgroundImage: {
        'hero-stripe': 'linear-gradient(135deg, var(--tw-gradient-stops))',
        'key-gradient': 'linear-gradient(180deg, var(--tw-gradient-stops))',
      },
      letterSpacing: {
        'tight': '-0.02em',
        'normal': '0em',
        'wide': '0.02em',
        'wider': '0.04em',
      },
      borderRadius: {
        'none': '0px',
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '10px',
        'xl': '16px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
